"""Positional-encoding check: verify position embeddings vary across position.

Vision: sincos tables generated by the repo at construction (not stored in ckpts).
Text: learned BERT position embeddings stored in the FT / S2 checkpoints.
"""
import sys
import json
from pathlib import Path

import torch

ROOT = Path(__file__).parent.parent.parent
UMT_MM = ROOT / "models" / "unmasked_teacher" / "multi_modality"
sys.path.insert(0, str(UMT_MM))

CONFIG = dict(
    ft_ckpt=ROOT / "models/umt_ckpts/ret_ssv2_tpl_b16_25m.pth",
    s2_ckpt=ROOT / "models/umt_ckpts/b16_25m.pth",
    img_size=224,
    patch_size=16,
    embed_dim=768,
    frames_ft=12,   # exp/finetuning/ret_ssv2_tpl/b16_25m.py num_frames
    frames_s2=4,    # exp/pretraining/b16_25m.py num_frames
    out_dir=ROOT / "outputs/umt_mlm_check",
)


def vary_stats(table_2d):
    """How much rows of a (N, C) table vary across position index."""
    t = table_2d.float()
    norms = t.norm(dim=1)
    adj = (t[1:] - t[:-1]).abs()
    unit = torch.nn.functional.normalize(t, dim=1)
    cos = unit @ unit.T
    n = t.shape[0]
    off_diag = cos[~torch.eye(n, dtype=torch.bool)]
    uniq = len({tuple(r.tolist()) for r in t})
    return dict(
        shape=list(t.shape),
        pos_norm_min=round(norms.min().item(), 4),
        pos_norm_max=round(norms.max().item(), 4),
        adjacent_absdiff_max=round(adj.max().item(), 6),
        adjacent_absdiff_mean=round(adj.mean().item(), 6),
        offdiag_cos_min=round(off_diag.min().item(), 4),
        offdiag_cos_mean=round(off_diag.mean().item(), 4),
        offdiag_cos_max=round(off_diag.max().item(), 4),
        unique_rows=uniq,
        has_nan=bool(torch.isnan(t).any()),
    )


def vision_tables():
    """Build the repo's own sincos tables for each config (unmodified repo function)."""
    from models.backbones.vit.vit import get_sinusoid_encoding_table

    P = (CONFIG["img_size"] // CONFIG["patch_size"]) ** 2
    tables = {}
    for label, T in [("ft_video_T12", 12), ("s2_video_T4", 4)]:
        table = get_sinusoid_encoding_table(P * T, CONFIG["embed_dim"])  # ckpt_num_frame=-1 path
        tables[label] = table.squeeze(0)
    tables["image_path_196"] = get_sinusoid_encoding_table(P, CONFIG["embed_dim"]).squeeze(0)
    return tables, P


def temporal_stats(table_2d, P, T):
    """Does the flattened video table vary across the frame index, not just space?"""
    frames = table_2d.float().reshape(T, P, -1)
    unit = torch.nn.functional.normalize(frames, dim=2)
    same_patch_adjacent = torch.einsum("tpc,tpc->tp", unit[:, :-1], unit[:, 1:]).mean()
    identical_frame_pairs = sum(
        torch.equal(frames[i], frames[j]) for i in range(T) for j in range(i + 1, T)
    )
    return dict(
        same_patch_adjacent_frame_cos_mean=round(same_patch_adjacent.item(), 4),
        identical_frame_pairs=f"{identical_frame_pairs}/{T * (T - 1) // 2}",
    )


def text_tables():
    """Learned BERT position embeddings straight from each checkpoint."""
    out = {}
    for label, path, key in [
        ("ft", CONFIG["ft_ckpt"], "text_encoder.embeddings.position_embeddings.weight"),
        ("s2", CONFIG["s2_ckpt"], "text_encoder.bert.embeddings.position_embeddings.weight"),
    ]:
        sd = torch.load(path, map_location="cpu", weights_only=False)
        sd = sd.get("model", sd)
        out[label] = sd[key].float()
    return out


def main():
    out = {"source": "repo get_sinusoid_encoding_table (vision, not in ckpts); ckpt tensors (text)"}
    tables, P = vision_tables()
    for name, t in tables.items():
        out[f"vision_{name}"] = vary_stats(t)
        if name.startswith(("ft_video", "s2_video")):
            T = t.shape[0] // P
            out[f"vision_{name}"].update(temporal_stats(t, P, T))
    txt = text_tables()
    for label, t in txt.items():
        out[f"text_{label}_position_embeddings"] = vary_stats(t)
    out["text_ft_vs_s2_max_abs_diff"] = round((txt["ft"] - txt["s2"]).abs().max().item(), 6)
    return out


if __name__ == "__main__":
    result = main()
    CONFIG["out_dir"].mkdir(parents=True, exist_ok=True)
    json_path = CONFIG["out_dir"] / "pos_embed_check_raw.json"
    json_path.write_text(json.dumps(result, indent=2))
    print(f"saved {json_path}")
    for k, v in result.items():
        if isinstance(v, dict):
            print(k, "->", v)
