"""
Layer selector — Stage-1 probe for TimeSformer SAE layer selection.

Loads probe_config.json (generated by make_probe_config.py), extracts and caches
mean/max-pooled SAE features per layer, then fits linear probes and ranks layers.

Usage:
    uv run python notebooks/layer_selector.py
    uv run python notebooks/layer_selector.py --config /path/to/probe_config.json
"""

import json
import sys
from pathlib import Path

import torch
from sklearn.linear_model import LogisticRegression
from torch.utils.data import DataLoader

ROOT = Path(__file__).parent.parent
sys.path.insert(0, str(ROOT))
sys.path.insert(0, str(Path(__file__).parent))

from sae import BatchTopKSAE
from ToT_utils import MODEL_REGISTRY, SSv2ClipDataset


def load_probe_config(path: str) -> dict:
    with open(path) as f:
        return json.load(f)


def build_sae(cfg: dict, device: str) -> BatchTopKSAE:
    hidden_dim   = MODEL_REGISTRY[cfg["model_name"]]["hidden_dim"]
    num_patch    = MODEL_REGISTRY[cfg["model_name"]]["num_patch_tokens"]
    nb_concepts  = cfg["sae_expansion"] * hidden_dim
    top_k        = cfg["sae_k"] * num_patch
    return BatchTopKSAE(
        input_shape=hidden_dim, nb_concepts=nb_concepts,
        top_k=top_k, device=device,
    )


def load_sae_checkpoint(sae: BatchTopKSAE, layer: int, cfg: dict, device: str) -> None:
    stem      = f"sae_{cfg['sae_abbrev']}_k{cfg['sae_k']}_x{cfg['sae_expansion']}_l{layer}_job{layer}"
    ckpt_path = Path(cfg["output_path"]).parent / f"{stem}_best.pt"
    if not ckpt_path.exists():
        raise FileNotFoundError(f"Best checkpoint not found: {ckpt_path}")
    ckpt      = torch.load(ckpt_path, map_location=device, weights_only=False)
    epoch     = ckpt.get("epoch", "?")
    score     = ckpt.get("val_score")
    score_str = f"  val_score={score:.4f}" if score is not None else ""
    print(f"  Layer {layer}: best checkpoint = epoch {epoch}{score_str}")
    sae.load_state_dict(ckpt["sae_state_dict"])
    sae.running_threshold = ckpt.get("running_threshold")


def warmup_sae(sae: BatchTopKSAE, model, hook_storage: dict,
               warmup_clips: list, processor, cfg: dict, device: str) -> None:
    """Run warmup clips through SAE in train mode to seed running_threshold."""
    model_cfg  = MODEL_REGISTRY[cfg["model_name"]]
    paths      = [Path(cfg["video_dir"]) / f"{c['id']}.webm" for c in warmup_clips]
    dataset    = SSv2ClipDataset(paths, processor, model_cfg["num_frames"])
    loader     = DataLoader(dataset, batch_size=8, shuffle=False, num_workers=2)
    sae.train()
    with torch.no_grad():
        for pixel_values in loader:
            model(pixel_values=pixel_values.to(device))
            acts = hook_storage["activations"].detach()
            for i in range(acts.shape[0]):
                sae(acts[i].float())
    print(f"    warmup done — running_threshold={sae.running_threshold:.4f}")


def extract_layer_features(layer: int, cfg: dict, device: str) -> Path:
    """Extract mean- and max-pooled SAE features for all probe clips at one layer.
    Returns path to the cache file. Skips if already cached."""
    cache_path = Path(cfg["output_path"]).parent / f"probe_features_l{layer}.pt"
    if cache_path.exists():
        print(f"  Layer {layer}: cache found, skipping extraction")
        return cache_path

    from train_sae import setup_model  # local import to avoid circular at module level

    model_cfg = MODEL_REGISTRY[cfg["model_name"]]
    probe_cfg = dict(cfg, layer=layer, hidden_dim=model_cfg["hidden_dim"],
                     num_patch_tokens=model_cfg["num_patch_tokens"],
                     num_frames=model_cfg["num_frames"],
                     nb_concepts=cfg["sae_expansion"] * model_cfg["hidden_dim"],
                     top_k=cfg["sae_k"] * model_cfg["num_patch_tokens"],
                     model_name=cfg["model_name"])

    model, processor, hook_storage = setup_model(probe_cfg)
    sae = build_sae(cfg, device)
    load_sae_checkpoint(sae, layer, cfg, device)
    warmup_sae(sae, model, hook_storage, cfg["warmup_clips"], processor, cfg, device)
    sae.eval()
    return _run_extraction(sae, model, hook_storage, processor, layer, cfg, device, cache_path)


def _run_extraction(sae, model, hook_storage, processor, layer, cfg, device, cache_path) -> Path:
    model_cfg   = MODEL_REGISTRY[cfg["model_name"]]
    all_clips   = cfg["train_clips"] + cfg["test_clips"]
    paths       = [Path(cfg["video_dir"]) / f"{c['id']}.webm" for c in all_clips]
    dataset     = SSv2ClipDataset(paths, processor, model_cfg["num_frames"])
    loader      = DataLoader(dataset, batch_size=8, shuffle=False, num_workers=2)
    mean_feats, max_feats = [], []

    print(f"  Layer {layer}: extracting {len(all_clips):,} clips...")
    with torch.no_grad():
        for pixel_values in loader:
            model(pixel_values=pixel_values.to(device))
            acts = hook_storage["activations"].detach()
            for i in range(acts.shape[0]):
                _, codes, _ = sae(acts[i].float())
                mean_feats.append(codes.mean(0).cpu())
                max_feats.append(codes.max(0).values.cpu())

    torch.save({"mean": torch.stack(mean_feats), "max": torch.stack(max_feats)}, cache_path)
    print(f"  Layer {layer}: saved → {cache_path}")
    return cache_path


def run_probe(features, labels, n_train: int, sklearn_cfg: dict) -> float:
    clf = LogisticRegression(
        C=sklearn_cfg["sklearn_C"],
        solver=sklearn_cfg["sklearn_solver"],
        max_iter=sklearn_cfg["sklearn_max_iter"],
        multi_class="multinomial",
        n_jobs=-1,
    )
    clf.fit(features[:n_train], labels[:n_train])
    preds = clf.predict(features[n_train:])
    return float((preds == labels[n_train:]).mean())


def main(config_path: str | None = None) -> None:
    cfg_path = config_path or str(ROOT / "outputs" / "sae" / "probe_config.json")
    cfg      = load_probe_config(cfg_path)
    device   = "cuda" if torch.cuda.is_available() else "cpu"
    print(f"Device: {device}  |  config: {cfg_path}")

    for layer in cfg["layers"]:
        extract_layer_features(layer, cfg, device)

    all_clips = cfg["train_clips"] + cfg["test_clips"]
    labels    = [c["class_id"] for c in all_clips]
    n_train   = len(cfg["train_clips"])

    results = {}
    for layer in cfg["layers"]:
        cache = torch.load(
            Path(cfg["output_path"]).parent / f"probe_features_l{layer}.pt",
            weights_only=True,
        )
        for pool in cfg["pooling"]:
            feats = cache[pool].numpy()
            print(f"  Fitting probe layer={layer} pool={pool}...")
            results[(layer, pool)] = run_probe(feats, labels, n_train, cfg)

    _print_and_save_results(results, cfg)


def _print_and_save_results(results: dict, cfg: dict) -> None:
    import csv
    layers = cfg["layers"]

    for pool in cfg["pooling"]:
        ranked = sorted(layers, key=lambda l: results[(l, pool)], reverse=True)
        print(f"\n--- {pool}-pool ranking ---")
        for l in ranked:
            print(f"  Layer {l:2d}  top-1={results[(l, pool)]:.4f}")

    mean_winner = max(layers, key=lambda l: results[(l, "mean")])
    max_winner  = max(layers, key=lambda l: results[(l, "max")])
    print(f"\nPrimary (mean): layer {mean_winner}")
    if mean_winner != max_winner:
        print(f"⚠ DISAGREEMENT — max-pool selects layer {max_winner}. Carry both to Stage 2.")

    out_csv = Path(cfg["output_path"]).parent / "probe_results.csv"
    with open(out_csv, "w", newline="") as f:
        w = csv.writer(f)
        w.writerow(["layer", "pool", "top1_accuracy"])
        for (layer, pool), acc in sorted(results.items()):
            w.writerow([layer, pool, f"{acc:.6f}"])
    print(f"\nSaved → {out_csv}")


if __name__ == "__main__":
    cfg_arg = sys.argv[1] if len(sys.argv) > 1 else None
    main(cfg_arg)
